"""
LAMMPS Lowered IR — near-LAMMPS-command intermediate representation.

This is the last IR stage before text rendering.
Each LAMMPSCommand is a single line of LAMMPS input with metadata.
"""

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class LAMMPSCommand:
    """A single LAMMPS command in lowered form."""
    kind: str         # "units", "atom_style", "pair_style", "fix", "run", etc.
    args: list[str] = field(default_factory=list)
    comment: str = ""
    line_number: int = 0  # Filled during topological sort

    def render(self) -> str:
        """Render this command as a LAMMPS input line."""
        parts = [self.kind] + [str(a) for a in self.args]
        line = " ".join(parts)
        if self.comment:
            line += " " + self.comment
        return line


@dataclass
class LAMMPSLoweredIR:
    """Ordered list of LAMMPS commands ready for text rendering."""
    commands: list[LAMMPSCommand] = field(default_factory=list)
    metadata: dict = field(default_factory=dict)

    def render(self) -> str:
        """Render all commands as a complete LAMMPS input script."""
        lines = []
        lines.append("# " + "=" * 40)
        lines.append("# LAMMPS input script generated by MDSynth v0.1.0")
        if self.metadata.get("task_type"):
            lines.append(f"# Task type: {self.metadata['task_type']}")
        if self.metadata.get("material"):
            lines.append(f"# Material: {self.metadata['material']}")
        lines.append("# " + "=" * 40)
        lines.append("")

        for cmd in self.commands:
            lines.append(cmd.render())

        return "\n".join(lines) + "\n"
