"""
Report templates for evidence package.

Templates for:
- README.md (human-readable summary)
- assumptions.md (assumptions and risks)
- semantic_diff.md (repair history)
"""


README_TEMPLATE = """# {task_display_name} Simulation

## Generated by MDSynth v0.1.0

**Date**: {generated_at}
**Task type**: {task_type}
**Material**: {material_name} ({material_symbol})
**Crystal structure**: {crystal_structure}, a = {lattice_constant} Å

## User Request

> {user_request}

## Simulation Summary

- **System**: {num_atoms} atoms, {replication_x}×{replication_y}×{replication_z} unit cells
- **Force field**: {force_field_family} ({potential_file})
- **Timestep**: {timestep} ps ({timestep_fs} fs)
- **Units**: metal (eV, Å, ps, K, bar)
- **Number of stages**: {num_stages}

## Protocol

{protocol_summary}

## Key Assumptions

{assumptions}

## Limitations

{limitations}

## Validation

- **Static validation**: {static_validation}
- **Preflight check**: {preflight_status}

## Files

- `in.main.lammps` — Main LAMMPS input script
- `md_ir.yaml` — MD Typed IR (machine-readable)
- `intent_spec.yaml` — Scientific Intent Spec
- `validation_report.json` — Full validation report
- `preflight_report.json` — Sandbox preflight report
- `provenance.lock` — Provenance manifest
- `assumptions.md` — Assumptions and risk analysis
- `forcefield_manifest.yaml` — Force field provenance

## How to Run

```bash
lmp -in in.main.lammps
```

## Reproducibility

This simulation was generated deterministically from a scientific intent
specification. All default values, assumptions, and repair actions are
documented in `provenance.lock` and `assumptions.md`.
"""


ASSUMPTIONS_TEMPLATE = """# Assumptions and Risks

## Assumptions Made

{assumptions_list}

## Risk Analysis

{risks_list}

## Default Values Applied

{defaults_list}

## Force Field Notes

{force_field_notes}

## Repair History

{repair_history}
"""


SEMANTIC_DIFF_TEMPLATE = """# Repair History (Semantic Diff)

This file documents all automatic repairs applied to the MD Typed IR
during the validation-repair loop.

{repair_entries}

## Summary

- Total repairs: {total_repairs}
- Permission A (syntax): {count_a}
- Permission B (structural): {count_b}
- Permission C (numerical): {count_c}
- Permission D (blocked — requires user): {count_d}
- Permission E (blocked — no physical basis): {count_e}
"""


def build_readme(**kwargs) -> str:
    """Build README.md from template."""
    return README_TEMPLATE.format(**kwargs)


def build_assumptions(**kwargs) -> str:
    """Build assumptions.md from template."""
    return ASSUMPTIONS_TEMPLATE.format(**kwargs)


def build_semantic_diff(**kwargs) -> str:
    """Build semantic_diff.md from template."""
    return SEMANTIC_DIFF_TEMPLATE.format(**kwargs)
