"""
MD Typed IR — the core intermediate representation of the entire system.

This is a typed simulation experiment design that expresses:
- WHAT system to build (structure, species, cell)
- WHAT interactions to use (force field)
- WHAT protocol to follow (stages: minimization, equilibration, deformation)
- WHAT to observe (observables, analysis)
- WHAT to output (thermo, dump, restart)

It does NOT contain LAMMPS commands — those are generated by the backend compiler.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, Literal

from mdsynth.utils.quantities import Quantity, QuantityRange, BoundaryCondition, BoundaryType, Dimension


# ============================================================
# Structure / System IR
# ============================================================

class StructureSourceType(str, Enum):
    GENERATED = "generated"
    FILE = "file"


@dataclass
class CrystalGenerator:
    """Parameters for generating a crystal structure."""
    lattice_type: str  # "fcc", "bcc", "hcp"
    lattice_constant: Quantity  # Å
    replication: tuple[int, int, int] = (10, 10, 10)


@dataclass
class StructureSpec:
    """Specification of how to obtain the atomic structure."""
    source: StructureSourceType
    generator: Optional[CrystalGenerator] = None
    file_path: Optional[str] = None
    file_checksum: Optional[str] = None


@dataclass
class Species:
    """A chemical species in the simulation."""
    element: str
    role: str = "bulk_atom"
    mass: Optional[Quantity] = None


@dataclass
class SystemIR:
    """Description of the material system to simulate."""
    material_name: str = ""
    material_class: str = "metal"
    structure: Optional[StructureSpec] = None
    species: list[Species] = field(default_factory=list)
    total_atoms: Optional[int] = None


# ============================================================
# Force Field IR
# ============================================================

class ForceFieldFamily(str, Enum):
    EAM = "eam"
    MEAM = "meam"
    TERSOFF = "tersoff"
    LJ = "lj"


@dataclass
class PotentialFile:
    """A potential file reference."""
    name: str
    source: str = "builtin"  # "builtin" | "user_upload" | "openkim"
    checksum: Optional[str] = None


@dataclass
class ForceFieldIR:
    """Force field specification."""
    family: ForceFieldFamily = ForceFieldFamily.EAM
    atom_style: str = "atomic"
    pair_style: str = ""
    pair_style_args: list[str] = field(default_factory=list)
    potential_files: list[PotentialFile] = field(default_factory=list)
    elements_covered: list[str] = field(default_factory=list)
    verification_status: str = "unverified"  # "verified" | "user_supplied" | "unverified"
    provenance: str = ""
    notes: list[str] = field(default_factory=list)


# ============================================================
# Cell / Box IR
# ============================================================

@dataclass
class CellIR:
    """Simulation cell / box specification."""
    boundary: BoundaryCondition = field(default_factory=BoundaryCondition)
    pressure_control_allowed: dict[str, bool] = field(default_factory=dict)
    deformation_allowed: dict[str, bool] = field(default_factory=dict)

    def __post_init__(self):
        # Auto-derive pressure control allowance from boundary conditions
        if not self.pressure_control_allowed:
            self.pressure_control_allowed = {
                axis: getattr(self.boundary, axis) == BoundaryType.PERIODIC
                for axis in ("x", "y", "z")
            }
        # Default: all periodic directions can deform
        if not self.deformation_allowed:
            self.deformation_allowed = {
                axis: getattr(self.boundary, axis) == BoundaryType.PERIODIC
                for axis in ("x", "y", "z")
            }


# ============================================================
# Group IR
# ============================================================

class GroupSelectorType(str, Enum):
    ALL = "all"
    REGION = "region"
    TYPE = "type"
    SUBTRACT = "subtract"
    UNION = "union"
    INTERSECT = "intersect"


@dataclass
class RegionSpec:
    """A geometric region definition."""
    type: str  # "block", "sphere", "cylinder"
    args: dict = field(default_factory=dict)


@dataclass
class GroupIR:
    """A group of atoms for applying fixes or computes."""
    id: str
    selector_type: GroupSelectorType = GroupSelectorType.ALL
    region: Optional[RegionSpec] = None
    atom_types: Optional[list[int]] = None
    subtract_groups: list[str] = field(default_factory=list)
    description: str = ""


# ============================================================
# Protocol / Stage IR
# ============================================================

class EnsembleType(str, Enum):
    NVE = "nve"
    NVT = "nvt"
    NPT = "npt"


class StageType(str, Enum):
    ENERGY_MINIMIZATION = "energy_minimization"
    EQUILIBRATION = "equilibration"
    PRODUCTION = "production"
    DEFORMATION = "deformation"


@dataclass
class EnsembleSpec:
    """Thermodynamic ensemble specification."""
    type: EnsembleType = EnsembleType.NVT
    group: str = "all"
    temperature: Optional[Quantity] = None
    temperature_range: Optional[QuantityRange] = None
    # NPT specific
    pressure_control: Optional[dict[str, Optional[Quantity]]] = None
    # Damping parameters
    tdamp: Optional[Quantity] = None
    pdamp: Optional[Quantity] = None


@dataclass
class MinimizationSpec:
    """Energy minimization parameters."""
    energy_tolerance: Optional[Quantity] = None
    force_tolerance: Optional[Quantity] = None
    max_iterations: int = 10000
    max_evaluations: int = 100000


@dataclass
class DeformationSpec:
    """Deformation protocol specification."""
    mode: str = "uniaxial_tension"  # "uniaxial_tension" | "uniaxial_compression"
    axis: str = "x"  # "x", "y", "z"
    strain_rate: Optional[Quantity] = None
    max_strain: Optional[Quantity] = None
    thermostat: Optional[EnsembleSpec] = None


@dataclass
class ProtocolStage:
    """A single stage in the simulation protocol."""
    id: str
    type: StageType
    ensemble: Optional[EnsembleSpec] = None
    minimization: Optional[MinimizationSpec] = None
    deformation: Optional[DeformationSpec] = None
    duration: Optional[Quantity] = None
    nsteps: Optional[int] = None


# ============================================================
# Observable & Analysis IR
# ============================================================

@dataclass
class Observable:
    """An observable to track during simulation."""
    id: str
    type: str  # "thermodynamic_scalar", "tensor", "msd", "rdf", "per_atom"
    scope: str = "global"  # "global", "per_atom", "group"
    group: Optional[str] = None
    components: list[str] = field(default_factory=list)


@dataclass
class ThermoOutput:
    """Thermodynamic output configuration."""
    interval: int = 100
    fields: list[str] = field(default_factory=lambda: [
        "step", "temp", "pe", "ke", "etotal", "press", "vol", "lx", "ly", "lz"
    ])


@dataclass
class DumpOutput:
    """Dump/trajectory output configuration."""
    enabled: bool = True
    interval: int = 1000
    fields: list[str] = field(default_factory=lambda: ["id", "type", "x", "y", "z"])
    format: str = "custom"  # "custom", "xyz", "lammpstrj"


@dataclass
class OutputIR:
    """Output configuration."""
    thermo: ThermoOutput = field(default_factory=ThermoOutput)
    dump: DumpOutput = field(default_factory=DumpOutput)
    restart: bool = True
    restart_interval: Optional[int] = None  # None = only at end


@dataclass
class AnalysisStep:
    """Post-processing analysis step."""
    id: str
    type: str  # "linear_fit", "time_average", "msd_fit"
    inputs: dict = field(default_factory=dict)
    outputs: list[str] = field(default_factory=list)
    parameters: dict = field(default_factory=dict)


# ============================================================
# Top-level MD Typed IR
# ============================================================

@dataclass
class MDTypedIR:
    """
    MD experiment design — the core data structure of the system.

    This is NOT LAMMPS-specific. It expresses the MD experiment in
    physical/scientific terms that can be compiled to any MD backend.
    """

    # Metadata
    ir_version: str = "0.1.0"
    source_intent_id: str = ""
    task_type: str = ""

    # Simulation object
    system: SystemIR = field(default_factory=SystemIR)

    # Interactions
    force_field: ForceFieldIR = field(default_factory=ForceFieldIR)

    # Simulation box
    cell: CellIR = field(default_factory=CellIR)

    # Atom groups
    groups: list[GroupIR] = field(default_factory=list)

    # Simulation protocol
    stages: list[ProtocolStage] = field(default_factory=list)

    # Global parameters
    timestep: Optional[Quantity] = None
    units: str = "metal"

    # Observables to track
    observables: list[Observable] = field(default_factory=list)

    # Output configuration
    outputs: OutputIR = field(default_factory=OutputIR)

    # Post-processing analysis
    analysis: list[AnalysisStep] = field(default_factory=list)

    # Assumptions and provenance
    assumptions: list[str] = field(default_factory=list)
    provenance: dict = field(default_factory=dict)

    def has_stage_type(self, stage_type: StageType) -> bool:
        """Check if the IR contains a stage of the given type."""
        return any(s.type == stage_type for s in self.stages)

    def get_stages_by_type(self, stage_type: StageType) -> list[ProtocolStage]:
        """Get all stages of a given type."""
        return [s for s in self.stages if s.type == stage_type]

    def get_timestep_value(self) -> float:
        """Get the timestep value, defaulting to 0.001 ps (1 fs) for metal."""
        if self.timestep:
            return self.timestep.value
        return 0.001
